export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  metaTitle: string;
  metaDescription: string;
  heroHeadline: string;
  heroSubheadline: string;
  intro: string;
  benefits: string[];
  process: { step: string; description: string }[];
  sections: { heading: string; content: string }[];
  faqs: { question: string; answer: string }[];
  priceFrom?: string;
}

export const services: Service[] = [
  {
    slug: 'combi-boiler-installation',
    title: 'Combi Boiler Installation Sunderland',
    shortTitle: 'Combi Boiler Installation',
    metaTitle: 'Combi Boiler Installation Sunderland | From £1,895',
    metaDescription: 'Professional combi boiler installation in Sunderland from £1,895. Gas Safe registered engineers, next-day fitting available. Free no-obligation quotes.',
    heroHeadline: 'Combi Boiler Installation in Sunderland',
    heroSubheadline: 'Compact, efficient hot water on demand. Fitted from £1,895 by Gas Safe registered engineers with up to 10 years warranty.',
    intro: 'A combi boiler heats water directly from the mains the moment you turn on a tap. There is no hot water cylinder taking up space in your airing cupboard and no cold water tank in the loft. For the majority of Sunderland homes, particularly the terraced streets across Hendon, Roker, Millfield, and the East End, a combi is the most practical and cost-effective choice. Over 70% of boiler replacements in the UK are now combis, and for good reason.\n\nOur Gas Safe registered engineers fit combi boilers from Worcester Bosch, Vaillant, Baxi, and Ideal. Every installation includes a full system powerflush, a magnetic filter to protect your new boiler from sludge, and up to 10 years manufacturer warranty when fitted by our accredited team. We handle everything from the initial survey to warranty registration, and most installations are completed in a single day.\n\nIf you are replacing an older combi, upgrading from a back boiler, or converting from a system setup, we can advise on the right route. See our back boiler replacement page if you are upgrading from a back boiler behind a gas fire, or check our guide on combi vs system boilers for a full comparison of the two main types.',
    sections: [
      {
        heading: 'Choosing the Right Size Combi Boiler',
        content: 'The most important decision when choosing a combi boiler is getting the right output for your home. Too small and you will notice lukewarm water and slow-filling baths. Too large and you are paying for capacity you will never use.\nCombi boilers are rated in kilowatts (kW), and the figure that matters most is the hot water output, not the central heating output. For a typical 2 to 3 bedroom Sunderland terrace with one bathroom, a 25 to 28kW combi is usually the right fit. These models deliver around 10 to 12 litres of hot water per minute, which is plenty for a single shower or bath running at a time.\nIf your home has 3 to 4 bedrooms or you have an en-suite in addition to the family bathroom, step up to a 30 to 35kW model. The higher output means better flow rates, so you will not notice a drop in temperature if someone runs a tap downstairs while you are in the shower.\nFor larger properties with high hot water demand, it is worth considering whether a system boiler with an unvented cylinder might serve you better. We always assess your mains water pressure during the survey because combi boilers rely on decent incoming pressure. In parts of Sunderland, particularly older areas like Bishopwearmouth and around the city centre, mains pressure can vary. We will tell you honestly if a combi is the right choice for your specific property.'
      },
      {
        heading: 'Combi Boiler Brands We Install',
        content: 'We are accredited installers for the leading boiler manufacturers, which means we can offer extended warranties that you would not get from a non-accredited fitter.\nWorcester Bosch remains the most popular choice among our Sunderland customers. The Greenstar 4000 and 8000 ranges offer excellent reliability, quiet operation, and warranties of up to 12 years. Worcester consistently tops the Which? reliability surveys, and parts availability is never an issue.\nVaillant is another strong option, particularly the ecoTEC range. These boilers are German-engineered and known for their longevity. The ecoTEC exclusive Green iQ model offers smart connectivity and high efficiency ratings.\nBaxi offers solid mid-range options for homeowners who want a reliable boiler without the premium price tag. The Baxi 800 range is a capable performer with warranties up to 10 years.\nIdeal rounds out our range with the Vogue and Logic+ series. These are well-built boilers manufactured in Hull, making parts and service support straightforward.\nDuring your survey, our engineer will recommend a brand and model based on your property, budget, and hot water demands. We never push a particular brand for our benefit. The right boiler is the one that fits your home and your usage.'
      },
      {
        heading: 'What Is Included in the Price',
        content: 'Our combi boiler installation prices start from £1,895 and include everything you need for a complete, working system. There are no hidden extras or surprise costs on installation day.\nEvery installation includes the boiler itself, a condensate pipe run to an external drain, a magnetic system filter (such as a MagnaClean or Fernox TF1), a full system powerflush to remove sludge and debris from your radiators, a wireless room thermostat, and chemical inhibitor to protect the system going forward. We also include all necessary pipework modifications, flue installation, and the Gas Safe notification to your local authority.\nIf your boiler is staying in the same position as the old one, this is a straightforward swap. Moving the boiler to a new location, for example from the kitchen to the utility room, involves additional pipework and possibly a new flue route. We price this clearly during the survey so you know the full cost upfront.\nFor a detailed breakdown of new boiler costs in the Sunderland area, see our guide on new boiler cost in Sunderland, which covers pricing by brand, property size, and installation complexity. If cost is a concern, check whether you qualify for a free boiler grant under the ECO4 scheme, or explore our boiler finance options with 0% interest available.'
      },
      {
        heading: 'Why Combi Boilers Suit Sunderland Terraces',
        content: 'Sunderland has a high proportion of terraced housing, particularly the Victorian and Edwardian streets in Roker, Ashbrooke, and the East End, along with the post-war terraces in Farringdon, Thorney Close, and Pennywell. These properties share a common challenge: limited space.\nA combi boiler solves this neatly. Without the need for a hot water cylinder in the airing cupboard or a cold water tank in the loft, you free up valuable storage space. The boiler itself is compact enough to sit inside a standard kitchen cupboard. For smaller terraces and flats, this space saving can make a real difference.\nCombis also suit the typical terrace layout because the boiler is usually positioned on a kitchen wall with a short flue run through the exterior wall. This keeps installation costs down and avoids the need for long flue extensions that some properties require.\nThe efficiency gains are significant too. If your terrace currently has an old back boiler or a regular boiler with a gravity-fed hot water system, switching to a modern combi can cut your gas bills noticeably. A modern combi runs at over 90% efficiency compared to the 55 to 75% typical of older systems. Over a year, that difference adds up to hundreds of pounds.'
      },
      {
        heading: 'Installation Day: What to Expect',
        content: 'Knowing what happens on installation day helps you plan around the work. Here is what a typical combi boiler installation looks like in practice.\nOur engineers will arrive at the agreed time, usually between 8 and 9am. They will lay dust sheets to protect your flooring and furniture, then begin disconnecting and removing the old boiler. If you are having the new boiler fitted in the same position, the swap is fairly straightforward.\nThe old boiler goes into our van for proper disposal. We then fit the new boiler, connect the gas supply, install the flue through the external wall, and run the condensate pipe to a drain. A system powerflush cleans out your radiators and pipework, removing any built-up sludge that could damage the new boiler. We then fit the magnetic filter and fill the system with inhibitor.\nThe final stage is commissioning. We fire up the boiler, check for gas tightness, test the flow rates, bleed the radiators, and programme the thermostat. A straightforward swap typically takes 4 to 6 hours. If we are relocating the boiler or carrying out additional pipework, it may take a full day or extend into the following morning.\nYou will be without heating and hot water during the installation. We always aim to have everything working again before we leave for the day.'
      }
    ],
    benefits: [
      'Hot water on demand with no storage tank or cylinder required',
      'Compact size, fits inside a standard kitchen cupboard',
      'Reduced energy bills compared to older boiler systems, with over 90% efficiency',
      'Up to 10 or 12 years manufacturer warranty through our accredited installer status',
      'Next-day installation available for urgent replacements',
      'Full system powerflush and MagnaClean filter included in every installation',
      'Wireless room thermostat included as standard',
      'Gas Safe notification and warranty registration handled for you'
    ],
    process: [
      { step: 'Free Home Survey', description: 'We visit your property to assess your heating needs, check the flue route, test your mains water pressure, and recommend the right size and brand of combi boiler. This usually takes 30 to 45 minutes and there is no obligation.' },
      { step: 'Fixed Price Quote', description: 'You receive a written quote with no hidden costs. We explain every line item so you know exactly what you are paying for. The price you see is the price you pay, including the boiler, installation, powerflush, filter, thermostat, and all pipework.' },
      { step: 'Installation Day', description: 'Our Gas Safe registered engineers arrive on time, protect your home with dust sheets, remove the old boiler, and fit your new system. Most straightforward installations are completed in a single day, with heating and hot water restored before we leave.' },
      { step: 'Handover and Registration', description: 'We walk you through your new boiler controls and thermostat, answer any questions, register your warranty directly with the manufacturer, and complete the Gas Safe notification. You receive all documentation and warranty certificates before we go.' }
    ],
    faqs: [
      { question: 'How long does a combi boiler installation take?', answer: 'A straightforward swap, where the new boiler goes in the same position as the old one, typically takes 4 to 6 hours. If we need to relocate the boiler or carry out significant pipework changes, it can take a full day or extend into a second morning. We will confirm the expected timeframe during your survey.' },
      { question: 'What size combi boiler do I need for my home?', answer: 'For a 2 to 3 bedroom home with one bathroom, a 25 to 28kW combi is usually right. For 3 to 4 bedrooms with an en-suite, a 30 to 35kW model gives better flow rates. We test your mains pressure during the survey and recommend the right output for your specific property and water demand.' },
      { question: 'Will I lose hot water during the installation?', answer: 'Yes, your heating and hot water will be off during the installation while we disconnect the old boiler and fit the new one. We aim to have everything back on before we leave, usually by mid to late afternoon on a standard swap.' },
      { question: 'Do you offer finance on combi boiler installations?', answer: 'Yes, we offer 0% interest finance over 12 months and longer terms up to 10 years for lower monthly payments. There is no deposit required on most plans. See our boiler finance page for full details and example monthly costs.' },
      { question: 'Can I move my boiler to a different location during the installation?', answer: 'Absolutely. Many customers choose to move the boiler from a kitchen wall to a utility room, garage, or loft. This involves additional pipework and possibly a longer flue run, which we price separately during the survey. Relocating the boiler usually adds half a day to the installation time.' },
      { question: 'Which combi boiler brand is best?', answer: 'Worcester Bosch consistently tops reliability surveys and is our most popular choice. Vaillant offers excellent German engineering and smart controls. Baxi and Ideal provide strong mid-range options. The best brand for you depends on your budget, property, and hot water demands. We recommend based on what suits your home, not on our margins.' },
      { question: 'Do I qualify for a free boiler under the ECO4 scheme?', answer: 'You may qualify if you receive certain benefits such as Universal Credit, Pension Credit, or Child Tax Credits, and your home has an EPC rating of D or below. Check our free boiler grants page for full eligibility details, or call us and we can check for you in minutes.' },
      { question: 'What warranty do I get with a new combi boiler?', answer: 'As accredited installers, we can offer extended manufacturer warranties of up to 10 or 12 years depending on the brand and model. Worcester Bosch offers up to 12 years, Vaillant up to 10, and Baxi up to 10. The warranty covers parts and labour for the full term.' }
    ],
    priceFrom: '£1,895',
  },
  {
    slug: 'system-boiler-installation',
    title: 'System Boiler Installation Sunderland',
    shortTitle: 'System Boiler Installation',
    metaTitle: 'System Boiler Installation Sunderland | Gas Safe',
    metaDescription: 'System boiler installation in Sunderland for larger homes. Hot water to multiple bathrooms at once. Gas Safe registered, free quotes.',
    heroHeadline: 'System Boiler Installation in Sunderland',
    heroSubheadline: 'Powerful heating for larger homes. Hot water to multiple bathrooms simultaneously, without losing pressure.',
    intro: 'If your home has three or more bedrooms and two or more bathrooms, a system boiler is almost certainly the right choice. Unlike a combi, which heats water on demand, a system boiler works with a hot water cylinder to store a reserve of heated water. This means multiple taps, showers, and baths can run at the same time without any drop in temperature or pressure.\n\nSystem boilers are the go-to solution for larger Sunderland properties, from the detached and semi-detached homes across Cleadon, Whitburn, and Seaburn to the bigger family houses in Silksworth and Doxford. If your household regularly has the morning rush of showers, baths, and taps all running at once, a system boiler handles that demand comfortably.\n\nOur Gas Safe registered engineers install system boilers from Worcester Bosch, Vaillant, and Ideal, paired with high-quality unvented hot water cylinders. We size every system to match your household demands, so you get consistent hot water whenever you need it. For a detailed comparison with combi boilers, see our guide on combi vs system boilers.',
    sections: [
      {
        heading: 'When to Choose a System Boiler Over a Combi',
        content: 'The decision between a system boiler and a combi comes down to how much hot water your household uses at the same time. A combi heats water on demand, which works brilliantly for homes with one bathroom. But ask a combi to supply a shower upstairs and a hot tap in the kitchen simultaneously, and you will notice the temperature drop.\nA system boiler avoids this problem entirely. The hot water cylinder holds a large volume of pre-heated water, typically 150 to 300 litres depending on the cylinder size. When someone opens a tap or turns on a shower, the water comes from this stored supply. Multiple outlets can draw water at the same time without affecting each other.\nAs a general rule, if your home has two or more bathrooms, a system boiler will give you a noticeably better experience. The same applies if you have a large bath that takes a long time to fill on a combi, or if you frequently run the dishwasher and washing machine while someone is in the shower.\nSystem boilers are also compatible with solar thermal panels. If you have or plan to install solar thermal, the cylinder can store the solar-heated water alongside the boiler-heated supply, reducing your gas usage further.\nThe trade-off is that you need space for the cylinder. A standard unvented cylinder fits in an airing cupboard and is roughly the size of a large fridge. If space is genuinely tight, a combi may be the more practical option. Our survey assesses your property and usage to recommend the right system type honestly.'
      },
      {
        heading: 'Unvented Cylinders Explained',
        content: 'Modern system boiler installations use an unvented hot water cylinder rather than the older vented type. Understanding the difference helps you appreciate why the upgrade matters.\nAn older vented system relies on a cold water tank in the loft, which feeds the cylinder by gravity. This means the hot water pressure depends on how high the tank sits above your taps. In a bungalow or a property with limited loft space, that pressure can be disappointing, resulting in weak showers and slow-filling baths.\nAn unvented cylinder connects directly to the mains water supply, bypassing the loft tank entirely. This gives you mains-pressure hot water throughout the house. The difference is immediately noticeable, particularly in showers, where the strong, consistent pressure feels completely different from an old gravity-fed system.\nUnvented cylinders also remove the need for a cold water tank in the loft, freeing up that space and eliminating the risk of frozen or contaminated tank water during cold spells. The cylinder itself includes built-in safety features such as a temperature and pressure relief valve, an expansion vessel, and a tundish to safely discharge water if the system overheats.\nInstalling an unvented cylinder requires a qualified engineer with the appropriate G3 certification, which all of our installers hold. We fit cylinders from Megaflo, Telford, and Worcester Bosch to match the boiler and your household capacity needs.'
      },
      {
        heading: 'Sizing a System Boiler for Your Home',
        content: 'Getting the right size system boiler means matching the boiler output to your radiator load and the cylinder recovery time you need. Our engineers carry out a full heat loss calculation during the survey, but here is a rough guide to help you understand the options.\nFor a 3 to 4 bedroom home with up to 15 radiators and a 150 to 200 litre cylinder, a system boiler in the 18 to 25kW range is typically sufficient. The boiler needs to heat the radiators and recharge the cylinder, so the output must cover both demands.\nLarger properties with 15 to 20 radiators and a 200 to 300 litre cylinder will need a 25 to 35kW system boiler. This higher output ensures the cylinder reheats quickly after heavy use, so the second round of morning showers is just as hot as the first.\nThe cylinder size matters too. A 150 litre cylinder suits a home with two bathrooms and 3 to 4 people. For households with three bathrooms or 5 or more people, a 200 to 250 litre cylinder gives you a larger reserve of hot water.\nWe always test your mains water pressure during the survey. Unvented cylinders need a minimum incoming pressure to work properly, typically around 1.5 bar. If your mains pressure is low, we can discuss options such as a mains booster pump or alternative cylinder types.'
      },
      {
        heading: 'System Boiler Brands We Install',
        content: 'We install system boilers from the same trusted manufacturers as our combi range, with models specifically designed for cylinder-based systems.\nWorcester Bosch system boilers, particularly the Greenstar 4000 and 8000 Life ranges, are our most popular choice. They offer excellent build quality, quiet operation, and warranties up to 12 years when installed by an accredited fitter like us. Worcester also makes the Greenstore unvented cylinders, so the boiler and cylinder are designed to work together.\nVaillant system boilers from the ecoTEC range are another strong option. These are reliable, efficient, and offer smart connectivity through the Vaillant app. Warranties extend up to 10 years with accredited installation.\nIdeal system boilers, including the Vogue and Logic+ system ranges, offer solid performance at a competitive price point. They are manufactured in the UK and backed by good after-sales support.\nWe pair each system boiler with a properly sized unvented cylinder from Megaflo, Telford, or the boiler manufacturer. The combination is selected to match your property size, bathroom count, and household usage patterns. During the survey, we will explain why we are recommending a particular pairing and give you options at different price points.'
      },
      {
        heading: 'System Boiler Installation: What the Work Involves',
        content: 'A system boiler installation is a bigger job than a combi swap because it involves both the boiler and the hot water cylinder. Here is what to expect.\nIf you are replacing an existing system boiler and cylinder, the work is relatively straightforward. We remove the old units, fit the new boiler and cylinder in the same positions, and connect everything up. This typically takes one full day, occasionally extending into a second morning if pipework modifications are needed.\nIf you are converting from a regular (conventional) boiler with a vented cylinder and loft tank, there is additional work. We remove the loft tank and the old vented cylinder, fit the new unvented cylinder, and modify the pipework to work with the new setup. The boiler is replaced at the same time. This conversion typically takes 1.5 to 2 days.\nEvery system boiler installation includes a full system powerflush to remove sludge from your radiators and pipework, a magnetic filter to protect the new boiler, inhibitor chemicals, and a wireless programmer and room thermostat. We commission the boiler, test every radiator, check the hot water flow rates, and register your warranty before we leave.\nIf you are unsure whether a system boiler is right for your home, get in touch for a free survey. We will give you an honest recommendation based on your property, not on what costs more. You may also want to check whether you qualify for a free boiler grant under the ECO4 scheme, which can cover the full cost for eligible households.'
      }
    ],
    benefits: [
      'Hot water to multiple bathrooms simultaneously without losing pressure',
      'Mains-pressure hot water throughout the house with an unvented cylinder',
      'Compatible with solar thermal panels for lower energy bills',
      'No cold water tank needed in the loft, freeing up space',
      'Large stored hot water reserve, so you never run out during busy mornings',
      'Ideal for 3+ bedroom properties with two or more bathrooms',
      'Quiet operation, with the cylinder absorbing most of the system noise',
      'Extended warranties up to 12 years through our accredited installer status'
    ],
    process: [
      { step: 'Home Assessment', description: 'We survey your property to understand your hot water demands, count bathrooms and radiators, test mains water pressure, and recommend the right boiler and cylinder combination. This is free and carries no obligation.' },
      { step: 'Detailed Quotation', description: 'You receive a clear, itemised quote covering the boiler, cylinder, all pipework, controls, powerflush, and magnetic filter. No hidden costs. We explain every line so you can compare like for like with other quotes.' },
      { step: 'Professional Installation', description: 'Our Gas Safe registered team installs the boiler and cylinder, connects all pipework, carries out a full system powerflush, and fits the magnetic filter. Most installations take 1 to 2 days depending on complexity.' },
      { step: 'Testing and Handover', description: 'We test every radiator, check hot water flow rates at each bathroom, commission the boiler, programme the thermostat, and register your warranty with the manufacturer. You get full documentation before we leave.' }
    ],
    faqs: [
      { question: 'Is a system boiler better than a combi for my home?', answer: 'If you have two or more bathrooms and a busy household, a system boiler will give you a much better hot water experience. Combis struggle to supply multiple outlets at once, leading to temperature drops and weak flow rates. A system boiler stores hot water in a cylinder, so everyone gets consistent pressure and temperature.' },
      { question: 'How much space does a system boiler need?', answer: 'The boiler itself is a similar size to a combi and mounts on a wall. You also need space for the hot water cylinder, which is roughly the size of a tall fridge and typically sits in an airing cupboard. The good news is that you no longer need a cold water tank in the loft, so you gain that space back.' },
      { question: 'Can I keep my existing hot water cylinder?', answer: 'In some cases yes, but we usually recommend upgrading to an unvented cylinder. Older vented cylinders rely on gravity for pressure, which gives weak showers and slow bath fills. An unvented cylinder gives you mains-pressure hot water throughout the house. The improvement is immediately noticeable.' },
      { question: 'How much does a system boiler installation cost?', answer: 'A system boiler installation in Sunderland typically ranges from £2,800 to £4,500 depending on the brand, output size, and cylinder specification. Converting from a regular boiler with a loft tank involves additional work and sits at the higher end. We provide a fixed price after surveying your property.' },
      { question: 'How long does a system boiler installation take?', answer: 'A straightforward replacement of an existing system boiler and cylinder usually takes one full day. If we are converting from a regular boiler and removing a loft tank, allow 1.5 to 2 days. We confirm the expected timeframe in your quote.' },
      { question: 'Can a system boiler work with solar thermal panels?', answer: 'Yes, and this is one of the advantages of a system boiler over a combi. The hot water cylinder can accept heat from solar thermal panels alongside the boiler, reducing your gas usage. If you have or plan to install solar thermal, a system boiler is the right choice.' },
      { question: 'Do I qualify for a free system boiler under ECO4?', answer: 'You may qualify for a fully funded system boiler replacement under the ECO4 scheme if you receive qualifying benefits and your home has an EPC rating of D or below. Visit our free boiler grants page for full eligibility details, or call us for a quick check.' }
    ],
  },
  {
    slug: 'back-boiler-replacement',
    title: 'Back Boiler Replacement Sunderland',
    shortTitle: 'Back Boiler Replacement',
    metaTitle: 'Back Boiler Replacement Sunderland | From £2,500',
    metaDescription: 'Replace your old back boiler in Sunderland. Full removal, modern combi fitted. Gas Safe engineers, fireplace options explained. Free quotes.',
    heroHeadline: 'Back Boiler Replacement in Sunderland',
    heroSubheadline: 'Upgrade from your old back boiler to a modern, efficient system. Full removal, new boiler fitted, typically from £2,500.',
    intro: 'If your home still has a back boiler tucked behind the gas fire in the living room, you are not alone. Thousands of Sunderland properties, particularly the terraced and semi-detached houses built between the 1960s and 1980s across areas like Southwick, Pallion, Pennywell, Ford Estate, and Town End Farm, still rely on these outdated units. They were a clever solution in their day, using the heat from a gas fire to warm water for the radiators and hot taps. But they have long since passed their useful life.\n\nMost back boilers run at just 55 to 65% efficiency. A modern condensing boiler operates at over 90%. That gap means you are paying significantly more for gas than you need to, every single month. Back boilers are also increasingly difficult and expensive to repair because manufacturers stopped making parts years ago. When something breaks, a replacement is often the only realistic option.\n\nReplacing a back boiler is more involved than a standard boiler swap, which is why it is important to use an installer who has done it many times before. Our engineers have replaced hundreds of back boilers across Sunderland and the wider North East. We handle the full job: safe removal, fireplace reinstatement, new boiler installation, and all the pipework in between.',
    sections: [
      {
        heading: 'What Is a Back Boiler and Why Replace It?',
        content: 'A back boiler is a small boiler unit that sits behind a gas fire, usually in the living room chimney breast. When the gas fire is lit, the back boiler uses the heat to warm water, which then circulates through your radiators and supplies your hot taps via a hot water cylinder, usually located upstairs in the airing cupboard.\nBack boilers were installed widely from the 1960s through to the late 1980s, when they were phased out in favour of wall-mounted boilers. If your home was built or renovated during this period and you have a gas fire with a boiler behind it, that is a back boiler.\nThe case for replacement is straightforward. Back boilers are inefficient, converting only 55 to 65% of the gas they burn into useful heat. The rest goes up the chimney. A modern condensing boiler converts over 90%, so you are looking at efficiency gains of 25 to 35 percentage points. On a typical Sunderland gas bill, that translates to savings of several hundred pounds per year.\nBeyond efficiency, there is the reliability problem. Back boiler parts have not been manufactured for decades. When a component fails, finding a replacement often means sourcing second-hand parts with no warranty, or bodging a repair that will not last. Many heating engineers will no longer work on back boilers at all because of the liability involved.\nThere are also safety considerations. Older back boilers were not designed to the same standards as modern appliances. Annual servicing is essential but increasingly difficult. If your back boiler has not been serviced recently, it should be inspected as a priority.'
      },
      {
        heading: 'The Back Boiler Removal Process Step by Step',
        content: 'Removing a back boiler is a bigger job than a standard boiler replacement because the old unit is embedded in the chimney breast. Here is how our engineers approach it.\nDay one begins with isolating and disconnecting the gas supply, draining the heating system, and carefully removing the gas fire from the front of the fireplace. The back boiler unit is then disconnected from the pipework and lifted out. This can be physically demanding work because these units are heavy cast iron and often corroded into position.\nWith the back boiler removed, we cap the gas supply at the fireplace and begin preparing the chimney breast. If you want to keep the fireplace opening, we clean it up and fit a closure plate or decorative panel. If you prefer to close it off entirely, we can brick up the opening and plaster over it, leaving a flat wall.\nWe then run new pipework from the fireplace area to the new boiler location, which is typically the kitchen. This involves routing copper pipes through the property, usually under floorboards and through walls. The hot water cylinder pipework is also modified or, if you are switching to a combi, the cylinder is removed entirely.\nDay two focuses on fitting the new boiler in its new position, connecting the gas supply, installing the flue through an exterior wall, running the condensate pipe, and connecting all the heating pipework. We carry out a full system powerflush, fit a magnetic filter, and commission the new boiler. The full job typically takes two days, occasionally stretching to a third if the pipework route is particularly complex.'
      },
      {
        heading: 'What Happens to Your Fireplace',
        content: 'One of the most common questions we get about back boiler replacement is what happens to the fireplace afterwards. You have several options, and it is worth thinking about this before we start.\nOption one is a decorative gas fire or electric fire. Once the back boiler is removed, the fireplace opening can accommodate a modern gas fire or an electric fire insert. This is the most popular choice among our customers because it preserves the focal point in the living room. We can cap the gas supply ready for a gas fire fitter to install a new appliance, or we can fit an electric fire ourselves.\nOption two is closing the fireplace opening with a ventilated panel. This is a neat, cost-effective solution that seals the opening while maintaining ventilation to prevent damp in the chimney. You can then place furniture against the wall or fit a mantelpiece as a decorative feature.\nOption three is bricking up and plastering over the opening entirely. This gives you a flat, clean wall. Some homeowners prefer this if they want to mount a television on the chimney breast or simply want a modern look.\nOption four is restoring the original fireplace opening. If your home has an older brick or stone fireplace behind the back boiler surround, it may be worth exposing and restoring it. This can add real character and value to your property.\nWe discuss all these options during the survey and include your chosen approach in the fixed-price quote. The fireplace work is part of the overall job, not an extra.'
      },
      {
        heading: 'Back Boiler Replacement Cost Breakdown',
        content: 'Back boiler replacement costs more than a standard boiler swap because of the additional work involved. Here is what you can realistically expect to pay in the Sunderland area.\nA back boiler replacement with a new combi boiler fitted in the kitchen, including full removal, pipework, and basic fireplace closure, typically ranges from £2,500 to £3,500. The exact price depends on the distance between the old boiler position and the new one, the complexity of the pipework route, and the brand and size of the new boiler.\nThe boiler itself makes up a significant portion of the cost. A mid-range Worcester Bosch or Vaillant combi suitable for a 3-bedroom property costs around £900 to £1,200 at trade prices. Installation labour for a two-day job, including the back boiler removal, pipework, and boiler fitting, accounts for the rest.\nIf you want a gas fire installed in the old fireplace opening, budget an additional £400 to £800 depending on the fire chosen. Bricking up and plastering the opening typically adds £150 to £300.\nFor a full comparison of pricing options, see our guide on new boiler cost in Sunderland. You should also check whether you qualify for a free boiler replacement under the ECO4 scheme. Given Sunderland\'s high proportion of qualifying households, many back boiler replacements can be fully funded at no cost to the homeowner. Visit our free boiler grants page for eligibility details.'
      },
      {
        heading: 'The Efficiency Gains: Before and After',
        content: 'The efficiency improvement from replacing a back boiler is one of the most dramatic upgrades you can make to your home\'s energy performance. Let us put some numbers on it.\nA typical back boiler operates at around 55 to 65% efficiency. That means for every pound you spend on gas, 35 to 45 pence is wasted, disappearing up the chimney as hot exhaust gases. A modern condensing combi or system boiler operates at 90 to 94% efficiency, wasting only 6 to 10 pence per pound.\nFor an average Sunderland terraced house spending around £1,000 to £1,200 per year on gas for heating and hot water, replacing a 60% efficient back boiler with a 92% efficient combi could reduce that bill by roughly £300 to £400 per year. The exact saving depends on your usage, insulation levels, and the price of gas, but the direction is always significant.\nBeyond the gas bills, there are control improvements too. A back boiler gives you very limited control over your heating. The boiler runs when the fire is on, and you have basic timer controls at best. A modern boiler comes with a wireless room thermostat, a programmer, and often smart controls that learn your routine and adjust automatically. You heat your home when and how you want to, rather than having the system dictate terms.\nIf you are still using a back boiler, replacing it is one of the best investments you can make in your property. The payback period on the installation cost is typically 6 to 10 years through energy savings alone, and you get improved comfort, reliability, and safety from day one.\nTo arrange a free survey of your back boiler, get in touch via our contact page. We will assess the job, explain your options, and provide a fixed-price quote with no obligation.'
      }
    ],
    benefits: [
      'Cut your gas bills significantly by moving from 55-65% to over 90% efficiency',
      'Full removal and safe disposal of the old back boiler unit',
      'No more relying on a gas fire to heat your water and radiators',
      'Modern thermostatic and smart controls for room-by-room comfort',
      'Fireplace options included: decorative fire, closure panel, brick up, or restore',
      'Improve your EPC rating, adding value to your property',
      'Eliminate the worry of sourcing obsolete parts when something breaks',
      'All work completed by Gas Safe registered engineers over a typical two-day installation'
    ],
    process: [
      { step: 'Survey and Planning', description: 'We assess your back boiler setup, check the chimney breast, plan the best position for the new boiler, and map out the pipework route. We also discuss your fireplace options and include your preference in the quote.' },
      { step: 'Fixed Price Quote', description: 'You receive a comprehensive quote covering the back boiler removal, all pipework, the new boiler and installation, fireplace reinstatement, powerflush, filter, and controls. Everything itemised, nothing hidden.' },
      { step: 'Removal and Installation', description: 'Day one: we remove the gas fire and back boiler, prepare the fireplace, and route the new pipework. Day two: we fit the new boiler in its new location, connect everything, powerflush the system, and commission. Two days is typical.' },
      { step: 'Completion and Handover', description: 'Full system test, radiator balancing, controls setup, warranty registration, and Gas Safe notification. We walk you through your new system and leave you with all documentation.' }
    ],
    faqs: [
      { question: 'How long does a back boiler replacement take?', answer: 'Most back boiler replacements take two full days. Day one covers the removal, fireplace work, and pipework. Day two is for fitting and commissioning the new boiler. Complex pipework routes or extensive fireplace restoration can occasionally extend the job into a third day.' },
      { question: 'What happens to the fireplace after the back boiler is removed?', answer: 'You have several options. We can fit a closure panel to seal the opening, brick it up and plaster over it for a clean wall, prepare it for a new decorative gas or electric fire, or expose and restore the original fireplace if there is one behind the surround. We discuss all options during the survey and include your choice in the quote.' },
      { question: 'Is it worth replacing my back boiler?', answer: 'Yes. The efficiency gain alone, from around 60% to over 90%, typically saves several hundred pounds per year on gas bills. Beyond the savings, you get a reliable modern system with available parts, proper controls, and a manufacturer warranty. Back boilers are also increasingly difficult to service safely.' },
      { question: 'How much does a back boiler replacement cost?', answer: 'A full back boiler replacement in Sunderland, including removal, new combi boiler, pipework, and fireplace closure, typically ranges from £2,500 to £3,500. The exact cost depends on the pipework complexity and the boiler brand you choose. We provide a fixed price after surveying your property.' },
      { question: 'Can I get a free back boiler replacement through ECO4?', answer: 'Many Sunderland households qualify for a fully funded back boiler replacement under the ECO4 scheme. If you receive qualifying benefits and your home has an EPC rating of D or below, the entire job could be covered at no cost. Check our free boiler grants page for full eligibility details.' },
      { question: 'Where will the new boiler go?', answer: 'The new boiler is usually fitted in the kitchen on an external wall, which gives the shortest flue route. Other options include a utility room, garage, or even a bedroom cupboard. We recommend the best location during the survey based on pipework runs, flue options, and your preferences.' },
      { question: 'Do I need to replace the hot water cylinder too?', answer: 'If you are switching to a combi boiler, the hot water cylinder is removed entirely because a combi heats water on demand. If you prefer a system boiler with a cylinder, we will assess whether your existing cylinder can be reused or should be upgraded to an unvented model for better pressure.' },
      { question: 'Will the work be messy?', answer: 'We protect your flooring and furniture with dust sheets throughout the job. Removing a back boiler does generate some dust, particularly when working around the chimney breast. We clean up thoroughly at the end of each day and leave your home tidy. Any plastering or making good is included in the quote.' }
    ],
    priceFrom: '£2,500',
  },
  {
    slug: 'boiler-conversion',
    title: 'Boiler Conversion Sunderland',
    shortTitle: 'Boiler Conversion',
    metaTitle: 'Boiler Conversion Sunderland | System to Combi',
    metaDescription: 'Boiler conversion in Sunderland. Switch from system to combi, regular to combi, or upgrade. Gas Safe registered, free quotes.',
    heroHeadline: 'Boiler Conversion in Sunderland',
    heroSubheadline: 'Switch your boiler type to match how your home uses heating and hot water today. All conversion types handled.',
    intro: 'Your heating system was designed for the household that lived in your home when it was installed. But households change. Children move out and you no longer need a big hot water cylinder. You convert the loft and suddenly need better water pressure upstairs. You inherit a house with an ancient gravity-fed setup that belongs in a museum. Whatever the reason, a boiler conversion changes your system type to match how you actually live now.\n\nWe carry out all types of boiler conversion across Sunderland, from conventional boilers with loft tanks to modern combis, from combis to system boilers with unvented cylinders, and from old gravity-fed systems to pressurised setups. Each conversion involves different work, and we price each one transparently based on what your specific property needs.\n\nNot sure which direction to go? Our guide on combi vs system boilers covers the pros and cons of each type in detail. Or get in touch for a free survey and we will assess your property and give you an honest recommendation.',
    sections: [
      {
        heading: 'Types of Boiler Conversion Explained',
        content: 'There are several types of boiler conversion, each suited to different situations. Here is what each one involves and who it is for.\nConventional to combi is the most common conversion we carry out. A conventional (also called regular or heat-only) boiler works with a cold water tank in the loft and a hot water cylinder, usually in the airing cupboard. Converting to a combi means removing both the tank and the cylinder, fitting a combi boiler that heats water on demand from the mains. This is ideal for smaller households who no longer need a large stored hot water supply and want to free up the cupboard and loft space.\nSystem to combi is similar but slightly less involved. A system boiler already has no loft tank, but it does use a hot water cylinder. Removing the cylinder and fitting a combi gives you on-demand hot water and frees up the airing cupboard. This works well for homes that have dropped from two bathrooms to one, or where the hot water cylinder is simply wasting energy heating water that nobody uses.\nCombi to system is less common but important for growing households. If you have added a bathroom through a loft conversion or extension, your combi may no longer cope with the demand. Converting to a system boiler with an unvented cylinder gives you the stored hot water capacity to supply multiple bathrooms simultaneously.\nGravity-fed to pressurised is a broader upgrade that replaces an old gravity-fed system with a modern pressurised setup. This typically involves a new boiler, a new unvented cylinder, removal of loft tanks, and significant pipework modifications. The result is mains-pressure hot water throughout the house, replacing the weak trickle that gravity-fed systems are known for.'
      },
      {
        heading: 'When Conversion Makes Sense vs Like-for-Like',
        content: 'Not every boiler replacement needs to be a conversion. Sometimes replacing your existing boiler with a new one of the same type is the right call. Here is how to think about it.\nConversion makes sense when your circumstances have changed. If your conventional boiler served a family of five and now only two of you live there, you are heating a full cylinder of water every day that mostly goes unused. Converting to a combi eliminates that waste. Similarly, if you have poor water pressure from a gravity-fed system and dream of a proper power shower, converting to a pressurised system with an unvented cylinder is the answer.\nLike-for-like replacement makes sense when your current system type still matches your needs. If you have a system boiler with two bathrooms and a busy household, replacing it with a new system boiler is simpler, faster, and cheaper than converting to something else. The boiler is the problem, not the system design.\nCost is also a factor. A like-for-like swap is always cheaper than a conversion because there is less pipework to modify and no components to remove. A straightforward combi-to-combi swap might cost £1,895 to £2,800, while a conventional-to-combi conversion could run £2,500 to £3,800 because of the additional work involved.\nOur survey assesses both options and gives you a clear recommendation with pricing for each route. We will tell you honestly if a conversion is worth the extra cost for your situation, rather than defaulting to the more expensive option.'
      },
      {
        heading: 'What the Conversion Work Involves',
        content: 'The scope of work depends on the type of conversion. Here is what each one typically includes.\nFor a conventional-to-combi conversion, we drain and remove the cold water tank from the loft and the hot water cylinder from the airing cupboard. The pipework that connected these components is either rerouted or capped. We then fit the new combi boiler, usually in the kitchen, and connect it directly to the mains water supply and your existing radiator circuit. The heating pipework usually remains the same, but the hot water pipework changes significantly because the combi supplies hot water directly rather than drawing it from a cylinder.\nFor a system-to-combi conversion, the work is similar but without the loft tank removal. We drain and remove the hot water cylinder, modify the hot water pipework, and fit the combi.\nFor a combi-to-system conversion, we fit a new system boiler and install an unvented hot water cylinder. This requires running new pipework between the boiler and cylinder, installing safety discharge pipework for the unvented cylinder, and often upgrading the cold water supply to handle the mains-pressure cylinder. This is the most involved conversion and typically takes two days.\nAll conversions include a full system powerflush, magnetic filter, inhibitor, wireless thermostat, and Gas Safe notification. We handle the full job from start to finish and leave you with a system that works properly from day one.\nIf cost is a barrier, check whether you qualify for a free boiler replacement under the ECO4 scheme. Our boiler finance page also has options for spreading the cost with 0% interest available over 12 months.'
      },
      {
        heading: 'Typical Costs by Conversion Type',
        content: 'Boiler conversion costs in Sunderland vary depending on the type of conversion and how much pipework needs modifying. Here are realistic price ranges for 2026.\nConventional to combi conversion: £2,500 to £3,800. This is the most common conversion and involves removing the loft tank and cylinder, modifying the hot water pipework, and fitting a new combi boiler. The wide price range reflects the difference between a compact terrace with short pipework runs and a larger semi-detached with more complex routing.\nSystem to combi conversion: £2,200 to £3,200. Slightly less work than a conventional conversion because there is no loft tank to remove. The cylinder removal, pipework modifications, and new boiler installation make up the bulk of the cost.\nCombi to system conversion: £3,000 to £4,500. The most expensive conversion because it involves fitting both a new system boiler and a new unvented cylinder, plus all the associated pipework. The cylinder itself accounts for a significant portion of the cost.\nGravity-fed to pressurised conversion: £3,200 to £5,000. This comprehensive upgrade replaces the entire heating infrastructure. It is a larger investment but the improvement in water pressure and system control is dramatic.\nEvery quote we provide is fixed-price and itemised. There are no hidden costs or surprises on installation day. We survey your property, explain exactly what work is needed, and give you a clear price before any work begins. See our detailed guide on new boiler costs in Sunderland for more pricing context.'
      }
    ],
    benefits: [
      'Free up airing cupboard and loft space by removing tanks and cylinders',
      'Match your heating system to your current household size and needs',
      'Improve hot water pressure by switching from gravity-fed to mains-pressure',
      'Reduce energy waste from heating water you do not use',
      'All pipework modifications, removal work, and disposal included in the price',
      'Expert advice on the most cost-effective conversion for your property',
      'Full system powerflush, magnetic filter, and controls included',
      'Finance options available if you prefer to spread the cost'
    ],
    process: [
      { step: 'Consultation and Survey', description: 'We discuss how your household uses heating and hot water, survey your existing system, and recommend the best conversion type for your situation. We also quote a like-for-like replacement so you can compare the two approaches.' },
      { step: 'Recommendation and Quote', description: 'We provide a clear, itemised quote for the full conversion, including removal of redundant components, new boiler and any new cylinder, all pipework modifications, powerflush, filter, and controls. Fixed price, no surprises.' },
      { step: 'Conversion Work', description: 'Our Gas Safe registered team carries out the conversion, which typically takes 1 to 2 days depending on complexity. We protect your home throughout and clean up at the end of each day.' },
      { step: 'System Commissioning', description: 'Full testing of every radiator and hot water outlet, flow rate checks, controls programming, warranty registration with the manufacturer, and Gas Safe notification. We explain how your new system works before we leave.' }
    ],
    faqs: [
      { question: 'Can I convert from a system boiler to a combi?', answer: 'Yes, this is one of the most common conversions we carry out. We remove the hot water cylinder and connect the combi directly to the mains water supply. It works well for homes with one bathroom that no longer need the stored hot water capacity of a cylinder.' },
      { question: 'Will a conversion affect my radiators?', answer: 'Usually not. Your existing radiators and most of the heating pipework are typically compatible with the new boiler. We may recommend adding thermostatic radiator valves if your existing ones are outdated, and occasionally adding a radiator or two if you have extended your home since the original system was installed.' },
      { question: 'How much does a boiler conversion cost?', answer: 'Costs vary by conversion type. A conventional-to-combi conversion typically ranges from £2,500 to £3,800. A combi-to-system conversion is £3,000 to £4,500. We provide a fixed-price quote after surveying your property so there are no surprises.' },
      { question: 'How long does a boiler conversion take?', answer: 'Most conversions take 1 to 2 days. A straightforward system-to-combi swap is usually a single day. Conversions that involve fitting a new cylinder or extensive pipework modifications typically take 2 days. We confirm the timeframe in your quote.' },
      { question: 'Is it worth converting or should I just replace like for like?', answer: 'It depends on whether your current system type still suits your household. If your hot water demands have changed, conversion is often worth the extra cost. If the system type still works for you and only the boiler is the problem, like-for-like is simpler and cheaper. We quote both options so you can make an informed choice.' },
      { question: 'Do I qualify for a free conversion under the ECO4 scheme?', answer: 'If you receive qualifying benefits and your home has an EPC rating of D or below, the ECO4 scheme may cover the full cost of a boiler conversion. Check our free boiler grants page for details, or call us and we will check your eligibility in minutes.' },
      { question: 'What happens to the old tanks and cylinders?', answer: 'We remove and dispose of all redundant components as part of the conversion. The cold water tank from the loft, the hot water cylinder, and any associated pipework are all taken away. There is no additional charge for this disposal.' }
    ],
  },
  {
    slug: 'emergency-boiler-replacement',
    title: 'Emergency Boiler Replacement Sunderland',
    shortTitle: 'Emergency Replacement',
    metaTitle: 'Emergency Boiler Replacement Sunderland | Same-Day',
    metaDescription: 'Emergency boiler replacement in Sunderland. Boiler broken? Same-day response, next-day install available. No premium pricing. Call now.',
    heroHeadline: 'Emergency Boiler Replacement in Sunderland',
    heroSubheadline: 'Boiler broken beyond repair? Same-day response, next-day installation available. No premium pricing for emergency work.',
    intro: 'When your boiler fails in the middle of a North East winter, you need it sorted quickly. Not next week. Not after three engineers have visited to "assess the situation." You need someone who turns up today, gives you a straight answer, and can fit a new boiler as soon as possible.\n\nOur emergency boiler replacement service is designed for exactly this situation. We carry popular Worcester Bosch and Vaillant models on our vans, so if your old boiler is beyond economic repair, we can often have a new one fitted within 24 to 48 hours of your call. We do not charge premium pricing for emergency work. The boiler and installation cost the same whether it is a planned replacement or an urgent one.\n\nWe cover all of Sunderland and surrounding areas including Washington, Houghton-le-Spring, Seaham, and Chester-le-Street. If you are without heating or hot water right now, call us or visit our contact page. We prioritise households with no heating, particularly those with young children, elderly residents, or vulnerable members.',
    sections: [
      {
        heading: 'What to Do When Your Boiler Breaks Down',
        content: 'If your boiler has stopped working, here are the steps to take before you call anyone.\nFirst, check the obvious. Is there power to the boiler? Check the fuse board for a tripped switch. Is the gas supply on? Check other gas appliances in the house. Is the thermostat calling for heat? Turn it up to maximum temporarily to rule it out. Check the boiler pressure gauge. If it is below 1 bar, the system may have lost pressure, which is often fixable by topping up via the filling loop.\nIf the boiler is displaying an error code, make a note of it. This helps us diagnose the issue over the phone and decide whether a repair is possible or a replacement is needed.\nIf you can smell gas, turn off the gas supply at the meter, open windows, leave the house, and call the National Gas Emergency line on 0800 111 999. Do not use electrical switches or your phone inside the property. Gas leaks are serious and must be handled by the gas emergency service before any other work takes place.\nIf there is no gas leak but the boiler is simply not firing, it is safe to wait for our engineer. We aim to visit on the same day you call, or first thing the following morning at the latest. While you wait, we can advise on temporary heating options to keep your home warm.'
      },
      {
        heading: 'When Repair Makes Sense vs Replacement',
        content: 'Not every broken boiler needs replacing. Our engineer\'s first job is to assess whether a repair is viable and cost-effective.\nRepair usually makes sense if the boiler is under 10 years old, the fault is a common component failure like a fan, PCB, or diverter valve, the part is readily available, and the repair cost is under £400. In these cases, fixing the boiler is the sensible option, and we carry common parts on our vans for fast repairs.\nReplacement makes more sense if the boiler is over 12 to 15 years old, if it has needed multiple repairs in recent years, if the fault is on the heat exchanger (the most expensive component), or if parts are discontinued. There is a point where spending £300 to £500 on a repair for a boiler that is likely to need another repair in six months is simply throwing money away.\nWe are honest about this assessment because it is in nobody\'s interest to repair a boiler that is going to fail again soon. Equally, we will not tell you a £150 repair is a lost cause just to sell a new boiler. Our engineers give you a straight recommendation based on the age, condition, and fault, and the decision is always yours.\nIf replacement is the answer, we move quickly. Our aim is to get you from broken boiler to new installation in the shortest time possible.'
      },
      {
        heading: 'Our Emergency Replacement Timeline',
        content: 'Speed matters when you are without heating. Here is how our emergency process works, step by step.\nWhen you call, we arrange a same-day visit wherever possible. If you call in the morning, our engineer will usually be with you that afternoon. Evening calls are triaged, and we aim for first thing the next morning.\nThe engineer assesses your boiler and gives you a straight answer on the spot. If replacement is needed, you get an instant quote. No waiting for head office to email something through. The engineer knows the prices and can quote you there and then.\nIf we have your boiler model in stock on the van, we can often start the installation the same day or the following morning. We carry popular Worcester Bosch and Vaillant combi boilers in the most common sizes, covering the majority of Sunderland properties.\nFor less common boiler types or system boiler installations that require a cylinder, we typically source and install within 2 to 3 working days. We will be upfront about the timeline so you can plan accordingly.\nThroughout the process, we prioritise based on vulnerability. Households with no heating in winter, homes with babies, young children, elderly residents, or anyone with a medical condition that is affected by cold are always moved to the front of the queue. Let us know your situation when you call.'
      },
      {
        heading: 'Temporary Heating While You Wait',
        content: 'If we cannot install your new boiler on the same day, we will make sure you are not left in the cold.\nFor households that need immediate warmth, we can provide temporary electric heaters to keep your main living spaces warm while you wait for the installation. These are fan heaters or oil-filled radiators that plug into a standard socket and can keep a room comfortable overnight.\nIf you have an immersion heater on your hot water cylinder (common in homes with system or conventional boilers), we can show you how to use it to get hot water while the boiler is out of action. This runs on electricity rather than gas, so it is more expensive to run, but it means you can still have hot showers and baths.\nFor combi boiler households without a cylinder, you will be without hot water until the new boiler is fitted. We can recommend kettle-and-basin solutions for the interim. It is not glamorous, but it is temporary.\nWe also keep in close contact throughout the waiting period. You will have your engineer\'s direct number so you can check on progress. We know that waiting for a boiler in a cold house is stressful, and we do everything we can to minimise that wait.'
      },
      {
        heading: 'Finance and Grants for Emergency Situations',
        content: 'An unexpected boiler replacement is a significant unplanned expense. We offer several ways to manage the cost so that money worries do not leave you in a cold house longer than necessary.\nOur boiler finance page has full details of our payment options. The headline option is 0% interest over 12 months, meaning you pay exactly the cash price but spread across monthly payments. For lower monthly costs, we offer terms up to 10 years. No deposit is required on most plans, and the application process is quick, often with an instant decision.\nFor those on lower incomes or receiving benefits, the ECO4 scheme may cover the full cost of a replacement boiler at no charge. We can run an eligibility check during the emergency visit. If you qualify, we submit the application and the boiler is installed completely free. The ECO4 process typically takes 2 to 4 weeks from application to installation, which is not instant, but we can provide temporary heating in the meantime.\nSunderland City Council also runs occasional hardship funds and discretionary grants for residents in fuel poverty. Our team stays up to date with what is available and can point you in the right direction.\nThe important thing is: do not sit in a cold house because you are worried about the cost. Call us, and we will find a route to get your heating back on. Whether that is finance, a grant, or a phased payment arrangement, there are always options.\nVisit our contact page to arrange an emergency assessment. We aim to respond to all emergency calls within 2 hours during working hours, 7 days a week during the heating season.'
      }
    ],
    benefits: [
      'Same-day response when your boiler breaks down',
      'Next-day installation available on popular models carried in stock',
      'No premium pricing for emergency work, same cost as a planned replacement',
      'Popular Worcester Bosch and Vaillant models carried on our vans',
      'Temporary heating solutions provided if installation cannot happen immediately',
      'Available 7 days a week during the heating season',
      'Vulnerable households and families with young children prioritised',
      'Finance and ECO4 grant checks available during the emergency visit'
    ],
    process: [
      { step: 'Call Us', description: 'Ring our emergency line or fill in the form on our contact page. We aim to respond within 2 hours during working hours and arrange a same-day visit wherever possible. Let us know if you have vulnerable residents in the household so we can prioritise.' },
      { step: 'Quick Assessment', description: 'Our Gas Safe engineer visits your home, diagnoses the fault, and gives you a straight answer: repair or replace. If replacement is needed, you get an instant fixed-price quote on the spot. No waiting around for paperwork.' },
      { step: 'Fast Installation', description: 'If we have your boiler in stock, installation can start the same day or the following morning. For less common models, we aim for 2 to 3 working days. We provide temporary heating in the meantime if needed.' },
      { step: 'Back Up and Running', description: 'Full installation, system powerflush, controls setup, testing, and commissioning. Your heating and hot water are restored as quickly as possible. Warranty registration and Gas Safe notification are completed before we leave.' }
    ],
    faqs: [
      { question: 'How quickly can you replace my boiler in an emergency?', answer: 'We aim for next-day installation if we have your boiler model in stock, which covers the majority of Sunderland properties. In most cases, you will have heating and hot water back within 24 to 48 hours of your initial call. Less common boiler types may take 2 to 3 working days to source.' },
      { question: 'Do you charge more for emergency replacements?', answer: 'No. Our boiler prices and installation costs are the same whether it is a planned replacement or an emergency. We do not add call-out fees, urgency surcharges, or weekend premiums. The price you are quoted is the price you pay.' },
      { question: 'What if I cannot afford a new boiler right now?', answer: 'We offer several options. Our 0% interest finance over 12 months requires no deposit and lets you spread the cost into monthly payments. Longer terms up to 10 years are also available. We can also check your eligibility for a free boiler under the ECO4 scheme during the visit. See our boiler finance page for details.' },
      { question: 'Should I repair or replace my broken boiler?', answer: 'Our engineer will give you an honest assessment. Generally, if the boiler is under 10 years old and the repair is under £400, fixing it makes sense. For older boilers, boilers needing repeated repairs, or faults on expensive components like the heat exchanger, replacement is usually the better investment.' },
      { question: 'Do you work on weekends for emergency replacements?', answer: 'Yes. During the heating season (October to March), we offer emergency assessments 7 days a week. Installation can also take place on weekends for urgent cases. Outside the heating season, our weekend availability is more limited but we still prioritise genuine emergencies.' },
      { question: 'Can you provide temporary heating while I wait?', answer: 'Yes. We can provide temporary electric heaters for your main living spaces if we cannot install the new boiler on the same day. If your home has an immersion heater on the hot water cylinder, we can show you how to use it for hot water in the interim.' },
      { question: 'What boiler brands do you carry in stock for emergencies?', answer: 'We carry popular Worcester Bosch and Vaillant combi boilers in the most common sizes (25kW, 30kW, and 35kW). These cover the majority of homes in Sunderland. For system boilers or less common models, we typically source within 1 to 2 working days from our suppliers.' },
      { question: 'I have a baby at home and no heating. Will you prioritise me?', answer: 'Absolutely. Households with babies, young children, elderly residents, pregnant women, or anyone with a medical condition affected by cold temperatures are always moved to the front of our emergency queue. Let us know your situation when you call and we will make it a priority.' }
    ],
  },
  {
    slug: 'free-boiler-grants',
    title: 'Free Boiler Replacement Grants Sunderland',
    shortTitle: 'Free Boiler Grants',
    metaTitle: 'Free Boiler Grants Sunderland | ECO4 Scheme 2026',
    metaDescription: 'Check if you qualify for a free boiler in Sunderland under ECO4. Income-based eligibility. We handle the full application. Check now.',
    heroHeadline: 'Free Boiler Grants in Sunderland',
    heroSubheadline: 'The ECO4 scheme can fund a complete boiler replacement at no cost to you. Check your eligibility in 60 seconds.',
    intro: 'The Energy Company Obligation (ECO4) scheme requires large energy suppliers to fund energy efficiency improvements in homes that need them most. If you receive certain benefits or have a low household income, you could qualify for a brand new boiler installed completely free of charge. No hidden costs, no monthly payments, no catch.\n\nSunderland has one of the highest rates of ECO4 eligibility in England. The city ranks 28th out of 317 local authorities for deprivation, which means a significant proportion of households meet the qualifying criteria. If you live in areas like Hendon, Pallion, Pennywell, Southwick, Town End Farm, or Ford Estate, there is a strong chance you or your neighbours qualify.\n\nWe are an approved ECO4 installer covering Sunderland and the wider North East. Our team handles the entire process: checking your eligibility, submitting the funding application, surveying your property, and installing the new boiler. You do not need to deal with your energy company or fill in complex forms. We take care of everything from start to finish.',
    sections: [
      {
        heading: 'What Is the ECO4 Scheme?',
        content: 'ECO4 stands for the Energy Company Obligation, now in its fourth phase. It is a UK government scheme that legally requires the largest energy suppliers, including British Gas, EDF, E.ON, OVO, and Scottish Power, to fund energy efficiency improvements in qualifying homes.\nThe scheme launched in April 2022 and runs until March 2026, with an expected extension beyond that date. It targets properties with poor energy efficiency ratings (EPC D, E, F, or G) occupied by people on low incomes or receiving certain benefits.\nUnder ECO4, the energy companies fund the full cost of approved measures, including boiler replacements, insulation, and heating controls. The homeowner or tenant pays nothing. The funding comes directly from the energy companies as a condition of their operating licence, not from your taxes and not from your energy bills (beyond the small contribution already built into everyone\'s tariff).\nThe aim is to improve the energy efficiency of the least efficient homes in the country, reducing fuel poverty and carbon emissions at the same time. For Sunderland specifically, with its older housing stock, high proportion of terraced and semi-detached properties, and above-average deprivation levels, the scheme is particularly relevant.\nIt is worth noting that ECO4 is not a loan. There is nothing to pay back. If you qualify, you receive a new boiler with a full manufacturer warranty at zero cost to you.'
      },
      {
        heading: 'Who Qualifies for a Free Boiler?',
        content: 'There are two main routes to qualifying for a free boiler under ECO4: the benefits pathway and the LA Flex pathway.\nThe benefits pathway is the most straightforward. You qualify if anyone in your household receives one or more of the following: Universal Credit, Pension Guarantee Credit, Income-based Jobseekers Allowance, Income-related Employment and Support Allowance, Income Support, Child Tax Credits (with income under £16,480), Working Tax Credits, Housing Benefit, or Warm Home Discount (core group).\nIn addition to receiving a qualifying benefit, your home must have an Energy Performance Certificate (EPC) rating of D or below. Most older properties in Sunderland are rated D or E, so this is rarely a barrier. If you do not have a recent EPC, we can arrange one as part of the process.\nThe LA Flex pathway exists for households that do not receive qualifying benefits but are still in fuel poverty or on low incomes. Sunderland City Council has published its own LA Flex criteria, which typically include households with a combined income below a certain threshold, people with health conditions made worse by cold housing, and households spending a disproportionate amount of their income on energy.\nIf you are unsure whether you qualify, the quickest way to find out is to call us or fill in the short form on our contact page. We can check your eligibility in minutes over the phone. There is no obligation, and we are honest about whether you qualify or not.'
      },
      {
        heading: 'The LA Flex Pathway: For Those Not on Benefits',
        content: 'The LA Flex pathway is worth understanding in detail because it opens up ECO4 funding to a much wider group of Sunderland residents than the benefits pathway alone.\nLA Flex stands for Local Authority Flexible Eligibility. It allows local councils to identify households in their area that are living in fuel poverty or are vulnerable to the effects of cold homes, even if they do not receive the standard qualifying benefits.\nSunderland City Council has published a Statement of Intent outlining their LA Flex criteria. While specific criteria can change, they generally cover households with a combined income below the regional median who live in a property with an EPC of D or below, residents with health conditions that are worsened by living in a cold or damp home (such as respiratory conditions, cardiovascular disease, or conditions affecting mobility), elderly residents living alone in poorly insulated properties, and households referred by health professionals, social workers, or other frontline services.\nThe LA Flex route involves more paperwork than the standard benefits pathway because the council needs to verify your circumstances. We handle this process on your behalf, including gathering the necessary documentation and submitting the referral to the council for their declaration.\nIf you think you might qualify through LA Flex but are not sure, contact us. We process LA Flex applications regularly across Sunderland and can tell you quickly whether your situation is likely to be approved.'
      },
      {
        heading: 'What You Actually Receive',
        content: 'If you qualify for ECO4 funding for a boiler replacement, here is exactly what you receive at no cost.\nYou get a brand new A-rated condensing boiler from a leading manufacturer such as Worcester Bosch, Vaillant, Baxi, or Ideal. The specific brand and model depend on what suits your property, but all are high-quality, reliable boilers with full manufacturer warranties.\nThe installation includes everything: removal and disposal of the old boiler, all necessary pipework modifications, a system powerflush to clean your radiators, a magnetic filter to protect the new boiler, a wireless room thermostat, condensate pipe installation, flue installation, and Gas Safe notification.\nIf you are upgrading from a back boiler, the additional work (removal of the back boiler, fireplace reinstatement, extended pipework) is also covered. See our back boiler replacement page for details of what this involves.\nThe manufacturer warranty, typically 5 to 10 years depending on the brand, is yours. You are covered for parts and labour for the warranty period, just the same as if you had paid for the boiler yourself.\nECO4 may also fund additional energy efficiency measures alongside the boiler, such as loft insulation, cavity wall insulation, or heating controls upgrades, if your property needs them to reach its target EPC band.\nThe only thing you need to provide is access to your home for the survey and installation. There are no hidden costs, no contributions, and nothing to pay at any stage.'
      },
      {
        heading: 'The Application Process',
        content: 'We have streamlined the ECO4 application process to make it as simple as possible. Here is what happens from your first contact to installation.\nStep one is the eligibility check. You call us or fill in the short form on our contact page. We ask a few questions about your benefits, household income, and property, and tell you within minutes whether you are likely to qualify.\nStep two is documentation. If you appear eligible, we ask you to provide proof of benefits (such as a recent benefits letter or Universal Credit statement) and confirm your address details. For LA Flex applications, we may need additional documentation relating to your circumstances.\nStep three is the funding application. We submit your application to the relevant energy company for ECO4 funding. This typically takes 5 to 10 working days to process. We chase it up and keep you informed of progress.\nStep four is approval and survey. Once funding is approved, we book a survey of your property. Our engineer visits to assess your existing heating system, check flue routes, and recommend the right replacement boiler.\nStep five is installation. We schedule the installation at a time that suits you. The work is carried out by our Gas Safe registered engineers, typically in a single day for a combi boiler swap. Back boiler replacements take two days.\nStep six is completion. We commission the boiler, register the warranty, complete the Gas Safe notification, and file all the paperwork with the energy company. You sign off that the work has been completed to your satisfaction.\nThe whole process from first contact to installation typically takes 2 to 4 weeks, sometimes faster if the funding application is approved quickly.'
      },
      {
        heading: 'Other Grants and Schemes',
        content: 'ECO4 is the main route to a free boiler, but it is not the only financial support available.\nThe Boiler Upgrade Scheme (BUS) offers grants of £7,500 towards an air source heat pump or £5,000 towards a ground source heat pump. This is not a boiler grant in the traditional sense, but if you are considering a low-carbon heating system, it significantly reduces the cost. The BUS is available to homeowners in England and Wales and does not have the same income or benefits criteria as ECO4. It applies to properties replacing fossil fuel heating systems.\nThe Warm Home Discount provides a £150 annual discount on your electricity bill. It does not fund a new boiler, but it does help with overall energy costs. You may be automatically enrolled if you receive Pension Credit, or you can apply through your energy supplier if you are on a low income.\nSunderland City Council periodically offers additional support through local fuel poverty initiatives. These can include top-up funding for households that partially qualify for ECO4, referrals to charitable organisations that help with heating costs, and emergency support for households in crisis.\nIf you do not qualify for ECO4 or any of the above, our boiler finance options let you spread the cost of a new boiler with 0% interest over 12 months or longer terms. See our boiler finance page for full details.\nWhatever your financial situation, we can help you find a route to a new boiler. Get in touch via our contact page and we will explore every option available to you.'
      }
    ],
    benefits: [
      'Completely free boiler replacement for qualifying households, with nothing to pay',
      'We handle the full ECO4 application process from eligibility check to completion',
      'Available to homeowners and private tenants (with landlord consent)',
      'Covers the full installation including pipework, controls, powerflush, and filter',
      'Quick eligibility check with no obligation, takes just a few minutes',
      'Full manufacturer warranty included, same as a paid installation',
      'LA Flex pathway available for low-income households not on standard benefits',
      'Additional measures like insulation may also be funded under the same application'
    ],
    process: [
      { step: 'Eligibility Check', description: 'Call us or fill in the short form on our contact page. We check your benefits, income, and property details against the ECO4 criteria and tell you within minutes whether you are likely to qualify. There is no obligation at this stage.' },
      { step: 'Application', description: 'If you qualify, we gather the necessary documentation and submit the funding application to the relevant energy company on your behalf. This typically takes 5 to 10 working days to process. We keep you informed throughout.' },
      { step: 'Approval and Survey', description: 'Once funding is approved, we visit your property to survey your existing heating system and recommend the best replacement boiler. We explain what work will be involved and agree a date for installation.' },
      { step: 'Free Installation', description: 'Our Gas Safe registered engineers install your new boiler at no cost. The work includes removal of the old boiler, all pipework, powerflush, filter, controls, and commissioning. You receive a full manufacturer warranty and all documentation.' }
    ],
    faqs: [
      { question: 'Who qualifies for a free boiler grant?', answer: 'You may qualify if you receive benefits such as Universal Credit, Pension Credit, Child Tax Credits, Income Support, Income-based JSA, Income-related ESA, Housing Benefit, or the Warm Home Discount. Your home also needs an EPC rating of D or below. Low-income households not on benefits may qualify through the LA Flex pathway via Sunderland City Council.' },
      { question: 'Is the boiler really completely free?', answer: 'Yes. There are no hidden costs, no monthly payments, no contribution required, and nothing to pay back. The ECO4 scheme is funded by energy companies as a legal obligation. You receive a brand new boiler with a full manufacturer warranty at zero cost.' },
      { question: 'Can private tenants get a free boiler?', answer: 'Yes, but you will need your landlord to agree to the installation since they own the property. We can provide a letter explaining the scheme to your landlord, outlining that it costs them nothing and improves their property. Most landlords are happy to proceed once they understand the scheme.' },
      { question: 'How long does the ECO4 application take?', answer: 'From your initial enquiry to a fully installed boiler, the process typically takes 2 to 4 weeks. The main variable is the funding application, which takes 5 to 10 working days for the energy company to process. We handle all the paperwork to keep things moving.' },
      { question: 'What if I do not receive any benefits?', answer: 'You may still qualify through the LA Flex pathway. This route is for low-income households, people with health conditions worsened by cold housing, and other vulnerable groups identified by Sunderland City Council. Contact us and we can check whether the LA Flex criteria apply to your situation.' },
      { question: 'Can I choose which boiler I get?', answer: 'We recommend a boiler based on your property size, hot water demands, and heating system type. The boilers we install under ECO4 are the same quality brands we fit for paid installations, including Worcester Bosch, Vaillant, Baxi, and Ideal. You will not receive a budget or lesser brand just because the boiler is funded.' },
      { question: 'Does ECO4 cover back boiler replacements?', answer: 'Yes. Back boiler replacements, including the removal of the old unit, fireplace reinstatement, new pipework, and a modern combi or system boiler, can be fully funded under ECO4 if you qualify. The additional work involved does not change your eligibility or cost you anything extra.' },
      { question: 'What happens if I do not qualify for ECO4?', answer: 'If you do not meet the ECO4 criteria, we can still help you get a new boiler. We offer 0% interest finance over 12 months and longer terms with affordable monthly payments. We also check for any other grants or council schemes you might be eligible for. See our boiler finance page for all the options.' }
    ],
  },
  {
    slug: 'boiler-finance',
    title: 'Boiler Finance Sunderland',
    shortTitle: 'Boiler Finance',
    metaTitle: 'Boiler Finance Sunderland | 0% Interest Available',
    metaDescription: 'Spread the cost of a new boiler. 0% interest over 12 months or longer terms. No deposit. Monthly payments from £30. Apply today.',
    heroHeadline: 'Boiler Finance in Sunderland',
    heroSubheadline: 'Spread the cost of your new boiler with flexible finance. 0% interest over 12 months, no deposit, monthly payments from £30.',
    intro: 'A new boiler is one of the most important investments you can make in your home, but we understand that finding £2,000 to £4,000 upfront is not realistic for everyone. That is why we offer flexible finance options that let you spread the cost into manageable monthly payments, starting from as little as £30 per month.\n\nOur most popular option is 0% interest over 12 months. You pay exactly the same total as you would paying cash, just divided into 12 equal monthly instalments. For those who need lower monthly payments, we offer longer terms of up to 10 years with competitive interest rates. No deposit is required on most plans.\n\nBefore exploring finance, it is worth checking whether you qualify for a free boiler under the ECO4 scheme. Many Sunderland households are eligible for a fully funded replacement at no cost. Visit our free boiler grants page for a quick eligibility check. If you do not qualify for ECO4, finance is the next best route to a new boiler without a large upfront payment.',
    sections: [
      {
        heading: 'Finance Options Explained',
        content: 'We offer several finance options to suit different budgets and circumstances. All finance is provided through FCA-authorised lenders, and we are a credit broker, not a lender.\nOur 0% interest plan spreads the cost over 12 months with no interest and no fees. The total you pay is identical to the cash price. If your new combi boiler costs £2,400, you pay 12 monthly instalments of £200. This is our most popular option for customers who can afford a moderate monthly payment and want to avoid any interest charges.\nOur low-rate plan offers terms from 2 to 5 years at a representative APR that is typically between 5.9% and 9.9%, depending on the amount borrowed and your credit profile. Longer terms mean lower monthly payments but a higher total cost due to interest. We always show you the total amount payable alongside the monthly figure so you can make an informed decision.\nOur extended plan stretches payments over 5 to 10 years for the lowest possible monthly cost. This suits customers who need to keep monthly outgoings to a minimum. The APR on extended plans is typically between 7.9% and 12.9%. Monthly payments can be as low as £30, but the total cost over the full term will be higher than the cash price.\nWe also offer buy now, pay later options with selected lenders. These give you a deferred period, usually 6 or 12 months, before payments begin. Interest may accrue during the deferred period depending on the specific product, so we explain the terms clearly before you commit.'
      },
      {
        heading: 'Example Monthly Costs by Boiler Type',
        content: 'To give you a realistic idea of what monthly payments look like, here are some examples based on typical installation costs in Sunderland. These are illustrative figures and your actual payments will depend on your credit assessment and chosen term.\nCombi boiler installation at £2,400: on 0% over 12 months, that is £200 per month with nothing extra to pay. On a 3-year plan at 7.9% APR, monthly payments drop to around £75, with a total cost of approximately £2,700. On a 5-year plan at 9.9% APR, monthly payments are around £52, with a total cost of approximately £3,100.\nSystem boiler installation at £3,500: on 0% over 12 months, that is approximately £292 per month. On a 3-year plan at 7.9% APR, monthly payments are around £109, with a total cost of approximately £3,930. On a 5-year plan at 9.9% APR, monthly payments are around £76, with a total cost of approximately £4,560.\nBack boiler replacement at £3,000: on 0% over 12 months, that is £250 per month. On a 3-year plan at 7.9% APR, monthly payments are around £94, with a total cost of approximately £3,370. On a 5-year plan at 9.9% APR, monthly payments are around £65, with a total cost of approximately £3,900.\nThese examples show the trade-off clearly: shorter terms cost less overall, while longer terms reduce your monthly outgoing. We present all options during the quotation stage so you can choose the balance that works for your budget.'
      },
      {
        heading: 'The Finance Application Process',
        content: 'Applying for boiler finance is straightforward, and most customers receive a decision within minutes.\nThe process starts with your boiler quote. We survey your property, recommend the right boiler, and provide a fixed price. Once you have your quote, we discuss the finance options and help you choose the right term.\nYou then complete a short application form, either on a tablet during the survey or online from home. The form asks for standard information: your name, address, date of birth, employment status, and income. We do not need payslips or bank statements at this stage.\nThe lender runs a credit check and makes a decision. In most cases, this is instant. You will know within minutes whether you are approved and at what rate. If the initial lender cannot offer you a plan, we can submit to alternative lenders because we work with a panel rather than a single provider.\nOnce approved, you sign the credit agreement electronically and we schedule your installation. Your first monthly payment is not due until one month after the boiler is fitted, so you do not start paying before you have a working boiler.\nThe entire application process, from filling in the form to receiving a decision, usually takes under 10 minutes. There is no obligation to proceed after receiving the decision. You can take the offer away, think about it, and let us know when you are ready.'
      },
      {
        heading: 'Understanding APR and Total Cost',
        content: 'Finance involves some terminology that can be confusing. Here is a plain-English explanation of the key terms you will encounter.\nAPR stands for Annual Percentage Rate. It represents the total yearly cost of borrowing, including interest and any fees, expressed as a percentage. The higher the APR, the more expensive the borrowing. Our 0% plan has an APR of 0%, meaning it costs you nothing extra. Plans with interest have APRs typically between 5.9% and 12.9%.\nThe representative APR is the rate that at least 51% of successful applicants will receive. Your actual rate may be higher or lower depending on your credit score and circumstances. We always confirm your actual rate before you commit to anything.\nTotal amount payable is the full cost you will pay over the entire term, including the original amount borrowed plus all interest. This is the most important number to compare when choosing between terms. A lower monthly payment over a longer term will always result in a higher total amount payable.\nMonthly payment is the fixed amount you pay each month for the duration of the agreement. This stays the same throughout the term, so your budgeting is predictable.\nWe present all of these figures clearly on every finance quotation. We want you to understand exactly what you are signing up for, with no small print surprises. If anything is unclear, ask us and we will explain it in plain terms.'
      },
      {
        heading: 'Alternatives to Finance',
        content: 'Finance is not the only way to manage the cost of a new boiler. Here are some alternatives worth exploring before you commit to borrowing.\nECO4 grants are the obvious first port of call. If you receive qualifying benefits and your home has a poor EPC rating, you could get a new boiler installed completely free. Even if you think you might not qualify, it is worth checking because the eligibility criteria are broader than most people expect, particularly through the LA Flex pathway. See our free boiler grants page for details.\nThe Boiler Upgrade Scheme offers grants towards heat pumps. If you are considering a move away from gas altogether, a grant of £7,500 towards an air source heat pump significantly reduces the upfront cost. This is available to all homeowners, not just those on benefits.\nSunderland City Council occasionally runs discretionary energy efficiency grants and fuel poverty programmes. We stay aware of what is available and can advise whether anything is currently open.\nSome homeowners choose to use a 0% purchase credit card for the boiler cost and pay it off within the interest-free period. This can work well if you have good credit and the discipline to clear the balance before the promotional rate ends. However, it does not offer the same consumer protections as a regulated finance agreement.\nIf you are a landlord replacing a boiler in a rental property, the cost is an allowable expense against rental income for tax purposes. This does not reduce the upfront cost, but it does reduce the net cost after tax relief.\nWhatever route you choose, the important thing is not to delay a necessary boiler replacement because of cost concerns. An inefficient or unreliable old boiler costs you money every month in wasted gas, and a breakdown in winter creates a much bigger problem. Get in touch via our contact page and we will help you find the right approach for your situation.'
      }
    ],
    benefits: [
      '0% interest finance available over 12 months, paying the same total as cash',
      'Longer terms up to 10 years available for lower monthly payments',
      'No deposit required on most finance plans',
      'Quick online application with decisions usually in minutes',
      'Monthly payments from as little as £30 depending on the term and amount',
      'First payment not due until one month after your boiler is installed',
      'We work with a panel of FCA-authorised lenders to find the best option for you',
      'Spread the cost of any boiler installation, conversion, or back boiler replacement'
    ],
    process: [
      { step: 'Get a Quote', description: 'We survey your property and provide a fixed-price quote for your new boiler installation. The price is the same whether you pay cash or use finance. No inflated finance prices.' },
      { step: 'Choose Your Plan', description: 'We present all available finance options with clear monthly costs and total amounts payable. You pick the term that suits your budget. We explain the differences in plain English so you can compare confidently.' },
      { step: 'Quick Application', description: 'Complete a short form on a tablet or online. The lender runs a credit check and gives a decision, usually within minutes. If the first lender cannot help, we try alternative providers from our panel.' },
      { step: 'Installation', description: 'Once approved, we schedule your boiler installation at a convenient date. The work is carried out exactly the same as a cash installation. Your first monthly payment begins one month after the boiler is fitted.' }
    ],
    faqs: [
      { question: 'Is the 0% finance really interest-free?', answer: 'Yes. Our 12-month 0% plan has no interest, no fees, and no hidden charges. You pay the same total as you would paying the full cash price upfront, divided into 12 equal monthly instalments. The APR is 0%.' },
      { question: 'Do I need a deposit?', answer: 'No deposit is required on most of our finance plans. The full cost of the boiler and installation is spread across your monthly payments. Some extended-term products with certain lenders may have a small deposit option to reduce the monthly amount, but this is never mandatory.' },
      { question: 'What credit score do I need?', answer: 'Finance is subject to a credit check and affordability assessment. There is no fixed credit score threshold because each lender has different criteria. We work with a panel of lenders, so if one cannot help, we often find an alternative. We will tell you honestly if finance is unlikely to be approved based on your circumstances.' },
      { question: 'Can I pay off the finance early?', answer: 'Yes. You can settle your finance early at any time with no early repayment penalties. If you pay off a plan with interest early, you only pay interest up to the settlement date, not the full term. The lender will provide a settlement figure on request.' },
      { question: 'Is the boiler price the same whether I pay cash or use finance?', answer: 'Yes. We do not inflate our prices for finance customers. The cost of the boiler and installation is identical whether you pay the full amount upfront or spread it over monthly payments. The only additional cost on non-zero plans is the interest itself.' },
      { question: 'How long does the finance application take?', answer: 'The application form takes about 5 minutes to complete and the lender typically returns a decision within minutes. The whole process, from filling in the form to knowing your monthly payment, usually takes under 10 minutes. There is no obligation to proceed after receiving the decision.' },
      { question: 'What if I am declined for finance?', answer: 'If the first lender declines your application, we can submit to alternative lenders from our panel. If finance is not available, we can check whether you qualify for a free boiler under the ECO4 scheme, or discuss alternative payment arrangements. See our free boiler grants page for eligibility details.' },
      { question: 'Can I use finance for a back boiler replacement or conversion?', answer: 'Yes. Our finance options cover any boiler installation we carry out, including combi and system boiler installations, back boiler replacements, and boiler conversions. The same terms and rates apply regardless of the type of work.' }
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
